### PR TITLE
Terms of beta policy in writing style checks

### PR DESCRIPTION
**Pull request by adinakleine**
Acc. to our beta policy we need to add "closed beta" and "public beta" to the automated writing style checks.

### CODE REVIEW

**Comment by TohruKohrita** [comment]
Just wondering if we are allowed to simply say "beta" without closed or public, aside from the flag.

**If** not, we might also consider including this in the list. Something like the line 29. (I am assuming that Vale suggests based on this list.) After all, the attempt to use simple "beta" may occur as often as private beta and open beta.

**Comment by adinakleine** [comment]
> Just wondering if we are allowed to simply say "beta" without closed or public, aside from the flag.
> 
> **If** not, we might also consider including this in the list. Something like the line 29. (I am assuming that Vale suggests based on this list.) After all, the attempt to use simple "beta" may occur as often as private beta and open beta.
> 
> On the other hand (though this is not relevant to this PR any longer), if we are allowed to keep using simple "beta", we may need to clarify what it means. (Maybe it's already done. If so, sorry for my ignorance.)

If we use "beta" in the public docs, we do mean always "public beta".  So no need to add something for this.
The term "beta" will be explained in the API contract / beta policy.

**Review by nkuehn — APPROVED** [review]
looks good to me, we can always add more if an issue actually occurs.

**Comment by TohruKohrita** [comment]
> If we use "beta" in the public docs, we do mean always "public beta". So no need to add something for this.

Thanks for the clarification on the usage and the meaning of simple beta. 

> The term "beta" will be explained in the API contract / beta policy.

Right. In fact, this is where I first began to wonder about simple beta.

Anyways, thanks. (Also, fortunately we do not use the term beta so much in the doc. )

**Pull request merged**
