### PR TITLE
fix: markdown-fragment-to-react now includes rendered images

### PR DESCRIPTION
**Pull request by davifantasia**

### CODE REVIEW

**Comment by emmenko** [comment]
@davifantasia please see #660 (first step) and #661.

**Review by emmenko — COMMENTED** [review]
Thanks!
Don't forget the changeset

**Comment by nkuehn** [comment]
I chose to build it completely now to have the bugs off the table:  #663

**Comment by davifantasia** [comment]
Replaced by https://github.com/commercetools/commercetools-docs-kit/pull/663

**Pull request closed without merging**
