### PR TITLE
fix: expanding chapter are incorrectly expanding

### PR DESCRIPTION
**Pull request by gabriele-ct**

### CODE REVIEW

**Review by timonrey — APPROVED** [review]
👍🏼

**Review by timonrey — CHANGES_REQUESTED** [review]
I checked the preview and the snapshots and it seems like there is a problem with the expandable chapters when using a deep link into a site. It doesn't open the chapter on the left...they stay closed. You can also see that in the snapshots.

**Comment by gabriele-ct** [comment]
> I checked the preview and the snapshots and it seems like there is a problem with the expandable chapters when using a deep link into a site. It doesn't open the chapter on the left...they stay closed. You can also see that in the snapshots.

Thank you, I'll have a better look

**Comment by gabriele-ct** [comment]
> I checked the preview and the snapshots and it seems like there is a problem with the expandable chapters when using a deep link into a site. It doesn't open the chapter on the left...they stay closed. You can also see that in the snapshots.

Thank you for spotting the issue. I didn't spotted it since it happens only when deployed (it has to do with sitePrefix). Now it should be working as expected

**Review by timonrey — APPROVED** [review]
Thank you!

**Pull request merged**
