### PR TITLE
fix(theme): render release notes filters in overlay for small screens

### PR DESCRIPTION
**Pull request by emmenko**
image

### CODE REVIEW

**Comment by emmenko** [comment]
I can take a look at that.

**Comment by davifantasia** [comment]
Thanks for fixing this @emmenko .

I expected the filter overlay to have similar behaviours like the index nav overlay. But you included a close button and the transparent background does not close the overlay when clicked, is the different behaviour the expectation from design?

Screenshot 2020-05-18 at 10 30 27

**Comment by emmenko** [comment]
I haven't checked with design yet but the behavior is indeed different.

In the content index nav, you have link. So when you click on a link you want to overlay to be closed immediately.

In the filters, you want to overlay to stay open, because you can configure multiple filters. Hence the need for a close button.

**Comment by emmenko** [comment]
The last commit should fix things up: https://github.com/commercetools/commercetools-docs-kit/pull/442/commits/dd2cdd1a92a7e9e3006f71e17a339719f4f2a320

**Comment by nkuehn** [comment]
approved by merging it :-).  Thank you!

**Pull request merged**
