### PR TITLE
[New feature] Expandable chapters

### PR DESCRIPTION
**Pull request by timonrey**
closes https://github.com/commercetools/commercetools-docs/issues/3179

**This pull request**
- introduces expandable chapters
- changes the navigation data structure of the docs-smoke-test (please test the feature there)
- forks the sidebar implementation for self-learning and normal microsites
- introduces a new `isSelfLearning` flag in the siteMetadata

### CODE REVIEW

**Comment by gabriele-ct** [comment]
@zbalek would you be able to have a visual check on the expandable chapters implementation: https://docskit-ga-expandible-chapters.commercetools.vercel.app/documentation/

Thank you

**Comment by zbalek** [comment]
Hi @gabriele-ct 
- UI: Could we please try to decrease the spacing between the chapter dividers and chapter titles by 8px on each side? 🙏 It feels a little too much at the moment.  

- UX/Behavior: When I have expanded multiple chapters, when I click on a page, the other chapters close. Can we please keep them open? (Attached a recording of this)

https://github.com/commercetools/commercetools-docs-kit/assets/125564062/395c96c1-29a7-49b5-b736-79824cf17a00

**Comment by gabriele-ct** [comment]
@zbalek would you mind a second round of visual check: https://docskit-ga-expandible-chapters.commercetools.vercel.app/docs-smoke-test/

**Review by gabriele-ct — APPROVED** [review]

**Comment by zbalek** [comment]
UI: Can we perhaps try to go with black (UI Kit: color-solid) for both pages/subchapter titles (same as for the chapter titles)? The contrast between the black signs and grey pages name feels a little strong.

UX: When I open and close the Views chapter, the +/- sign jumps a bit. This doesn’t happen with the other chapters though.  

_Probably a note for the tech writers but if there are any pages in a chapter, they would go first and then the closed subchapters after._

https://github.com/commercetools/commercetools-docs-kit/assets/125564062/c5b66e8f-eb41-406d-9382-9770936a6eaf

**Comment by gabriele-ct** [comment]
Thank you for your feedback @zbalek 

> UI: Can we perhaps try to go with black (UI Kit: color-solid) for both pages/subchapter titles (same as for the chapter titles)? The contrast between the black signs and grey pages name feels a little strong.
> 
@timonrey  I think this is what you were also referring to. Would you be able to implement this change?

> UX: When I open and close the Views chapter, the +/- sign jumps a bit. This doesn’t happen with the other chapters though.  
>

That's unavoidable if we want to have the scrollbar automatically appearing/disappearing depending on the content length. A possible solution, as shopify does, keep the scrollbar always visible which would lead to the following result:

 
Screenshot 2023-09-07 at 12 33 37

From what I can see, using standard CSS is not possible to change width or color of the scrollbar. I guess using some custom React library might be possible but it would require investigation.

> _Probably a note for the tech writers but if there are any pages in a chapter, they would go first and then the closed subchapters after._
> 
>  Screen.Recording.2023-09-07.at.12.16.51.mov

**Comment by timonrey** [comment]
> UX/Behavior: When I have expanded multiple chapters, when I click on a page, the other chapters close. Can we please keep them open? (Attached a recording of this)

@zbalek which browser are you using? I can't reproduce it in chrome 🤔 
And I also updated the colors. Looks a bit heavy now with the black color for the pages...just let me know if you want to keep it or if we should stick to the grey color :)

**Comment by gabriele-ct** [comment]
> > UX/Behavior: When I have expanded multiple chapters, when I click on a page, the other chapters close. Can we please keep them open? (Attached a recording of this)
> 
> @zbalek which browser are you using? I can't reproduce it in chrome 🤔 And I also updated the colors. Looks a bit heavy now with the black color for the pages...just let me know if you want to keep it or if we should stick to the grey color :)

@timon This was part of the previous round of observations from Zoe and it's been fixed already. Please refer to this comment: https://github.com/commercetools/commercetools-docs-kit/pull/1812#issuecomment-1709928292

**Comment by zbalek** [comment]
thank you @timonrey - I'd like to test it with all black, but i see what you mean- let's see if we get some feedback on this from users

**Review by zbalek — APPROVED** [review]

**Comment by gabriele-ct** [comment]
@melindafekete you can have a look to the expandable chapters preview here: https://docskit-ga-expandible-chapters.commercetools.vercel.app/documentation/

We wait for your green light before adding it to the next release
Thank you

**Comment by melindafekete** [comment]
> @melindafekete you can have a look to the expandable chapters preview here: https://docskit-ga-expandible-chapters.commercetools.vercel.app/documentation/
> 
> We wait for your green light before adding it to the next release Thank you

Thanks @gabriele-ct is could we also test the expandable sub-chapter functionality? thank you!

**Comment by gabriele-ct** [comment]
Yes @melindafekete , you can test it here: https://docskit-ga-expandible-chapters.commercetools.vercel.app/docs-smoke-test/

**Comment by basebander** [comment]
FYI: The + and - are different sizes. The minus is slightly larger, but noticeable.

**Comment by melindafekete** [comment]
> Yes @melindafekete , you can test it here: https://docskit-ga-expandible-chapters.commercetools.vercel.app/docs-smoke-test/

Thanks, Gabriele! I think apart from what Ryan shared, we're good to go, but would definitely like to see it in action on commercetools-docs before we release the version upgrade. thank you! 🙌

**Comment by gabriele-ct** [comment]
> 1. The + and - are different sizes. The minus is slightly larger, but noticeable.

We discussed that with @zbalek , those icons come from iconset used throughout Commercetools so we agreed to keep it

> 2. When the scrollbar gets added to the view, the + - buttons move. I don't know if there is a solution for that one.

This was also part of the [discussion above](https://github.com/commercetools/commercetools-docs-kit/pull/1812#issuecomment-1709928292) and, at least for now, no action has been decided.

If @zbalek wants to add something, otherwise I'll consider the ticket ready to be released and further improvements will be added as separate tickets

**Comment by zbalek** [comment]
Hi @gabriele-ct, following a discussion with the tech writers, could you please create a preview where we'd use chevrons instead of +/- signs?   🙏 We have them available in the UI kit as angle icons - potentially, to also address some concerns around the icon thickness - we could use thin angle icons for closed and regular for open (though the thin ones seem to be a bit too thin to match the regular Inter font).

cc/ @industrian

**Comment by industrian** [comment]
> Hi @gabriele-ct, following a discussion with the tech writers, could you please create a preview where we'd use chevrons instead of +/- signs? 🙏 We have them available in the UI kit as angle icons - potentially, to also address some concerns around the icon thickness - we could use thin angle icons for closed and regular for open (though the thin ones seem to be a bit too thin to match the regular Inter font).
> 
> cc/ @industrian

Example pages with chevrons/arrows:

https://react.dev/learn/adding-interactivity
https://docs.astro.build/en/getting-started/
https://angular.io/docs

**Comment by zbalek** [comment]
Hi @gabriele-ct 👋 I have now confirmed with the tech writers team that the +/- signs should be replaced with the chevrons as follows:

image

- In terms of the weight of the icons may be limited to what is currently in our [UI kit](https://uikit.commercetools.com/?path=/story/components-icons--all-icons) [AngleRightIcon, AngleDownIcon]. 
- We could potentially use the Lordicon icons (below) and have a thinner stroke for the right arrow [unselected] and thicker stroke for the down arrow [selected]. I tried to simulate the stroke in Figma but the SVG file didn't work well w/o further manipulation and so I'm not sure about the exact %. This one would require some discretion on your side to adjust the stroke with the font weight.

- https://lordicon.com/icons/wired/outline/31-arrow-right
- https://lordicon.com/icons/wired/outline/33-arrow-down

_I checked in with Adina today and the feature needs to be available by the COP on the 26th (Tuesday, next week). And so in interest of time we may go with what's in the UI Kit for now and have the weight adjustment using the Lordicon icons as a future improvement

cc @FFawzy - ticket unblocked

**Pull request merged**
