### PR TITLE
 refactor(theme): to render search results in an overlay, aligned with the page content

### PR DESCRIPTION
**Pull request by emmenko**

### CODE REVIEW

**Comment by emmenko** [comment]
Alright, Sven said it's ok now. @nkuehn would you like to have a final look?

**Comment by nkuehn** [comment]
@emmenko  I really like the way you interact with it, thanks!   The only minor complaint I find is that it has a slight height flicker when activating the search box for the first time.  I guess that's the algolia widget initializing itself empty.  Maybe reserve a minimum height?

**Comment by emmenko** [comment]
@nkuehn alright, I changed a bit how we load the search component. We lazy load it and use React.Suspense to determine if a loading state should be shown or not.

Below you can see it with an artificial delay of 2 sec:

**Comment by emmenko** [comment]
I'll merge once CI passes

**Pull request merged**
