### PR TITLE
Ga rebrand logo

### PR DESCRIPTION
**Pull request by gabriele-ct**

### CODE REVIEW

**Comment by gabriele-ct** [comment]
@zbalek
Please have a look to the rebranding icons
https://docskit-ga-rebrand-logo.commercetools.vercel.app/docs-smoke-test/

@FFawzy would you be able to replace the logo in the Auth0 interface? I add it as attachment 
ID logo

**Comment by zbalek** [comment]
@gabriele-ct - can you please also update the topbar logo (currently it seems that only the word "Documentation" has been updated but not the logo)?

**Comment by FFawzy** [comment]
@gabriele-ct Auth0 needs a url with the image .. so we can publish the image as a static asset then we can use the link, can we do that?

**Comment by gabriele-ct** [comment]
> @gabriele-ct - can you please also update the topbar logo (currently it seems that only the word "Documentation" has been updated but not the logo)?

Sorry @zbalek my bad. Now it should be good to go

**Comment by zbalek** [comment]
Thank you @gabriele-ct - looks good!

**Review by FFawzy — APPROVED** [review]
Thanks

**Pull request merged**
