### PR TITLE
fix: add dependency "assert" to fix development

### PR DESCRIPTION
**Pull request by timonrey**
local development is not working at the moment because of the missing `assert` dependency.

### CODE REVIEW

**Review by davifantasia — CHANGES_REQUESTED** [review]
Please add `assert` to the themes instead so we manage it from the themes only.

**Comment by emmenko** [comment]
Where is this dependency being used? What is exactly the error?

**Comment by timonrey** [comment]
Looks like webpack can't find the `assert` dependency.
Bildschirmfoto 2021-08-06 um 14 09 52

**Review by davifantasia — APPROVED** [review]
Thanks

**Comment by emmenko** [comment]
To clarify: the `assert` dependency is used by `mdast-util-from-markdown`, which in turn is used by `remark-parse` which was updated in #1071  (see also https://github.com/commercetools/commercetools-docs-kit/pull/1071/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR15370-R15385)

So, as a quick fix we can explicitly declare the dependency `assert`. However, we should [report the bug](https://github.com/syntax-tree/mdast-util-from-markdown/issues) and remove the dependency `assert` again once it's fixed upstream.

**Comment by timonrey** [comment]
Thanks for the clarification 💯

**Pull request merged**
