### PR TITLE
Code Highlighting: tune syntax highlight color scheme

### PR DESCRIPTION
**Pull request by nkuehn**
- swap the "neon" yellow for a less agressive one provided by design
 - swap two colors to improve JSON understandability
  - homogenize numbers and bools across light / dark to ease JSON understandability

@sven this is the experimental implementation of the color code you sent me plus improving the test examples plus a try to slightly homogenize the _JSON_  highlighting across light and dark. 

JSON is 80% of the example content that is initially read and seen so optimizing for JSON stands before other languages. 

(I'll send a deeplink to the test once it's built)

### CODE REVIEW

**Comment by davifantasia** [comment]
Closes https://github.com/commercetools/commercetools-docs-kit/issues/576

**Comment by davifantasia** [comment]
Should close https://github.com/commercetools/commercetools-docs-kit/issues/576

**Comment by nkuehn** [comment]
@Shecki    here's two pages you can check:
 * For the JSON examples (most important):  https://commercetools-docs-kit-git-nk-adjust-code-highlight-theme.commercetools.vercel.app/docs-smoke-test/components/code-blocks
 * For more variations :  https://commercetools-docs-kit-git-nk-adjust-code-highlight-theme.commercetools.vercel.app/docs-smoke-test/views/code-blocks

**Comment by Shecki** [comment]
for me, its fits perfectly.
what do you think? @nkuehn

**Pull request merged**
