### PR TITLE
fix(writing-style): use `TokenIgnores` instead of `BlockIgnores`

### PR DESCRIPTION
**Pull request by emmenko**
Attempt to fix the issue with Vale + MDX (JSX).

Previous attempt was done in #1321 but this introduced a regression (see #1341).

It seems thought that using `TokenIgnores` instead of `BlockIgnores` fixes both issues.

See examples below in docs-kit:

**Without ignore regex**

Screenshot 2022-10-22 at 15 12 27

**With `TokenIgnores` regex**

Screenshot 2022-10-22 at 15 13 04

I don't know if this was the actual original issue that led to #1321, maybe @nkuehn can confirm and double check.
Thanks!

### CODE REVIEW

**Review by timonrey — APPROVED** [review]

**Comment by emmenko** [comment]
@nkuehn Is this change ok for you as well?

**Comment by nkuehn** [comment]
I haven't found the time to analyze it for real but intuitively it feels more correct to me because JSX can be interleaved with markdown even inside what markdown considers a "Block"

**Comment by emmenko** [comment]
Should we give this a try or do you have other suggestions?

**Comment by gabriele-ct** [comment]
I'm fine with it. I'm going to merge this and we see how if goes. FYI @nkuehn

**Pull request merged**
